# Muc RAM toi uu cho may 8GB (Phai tat Chrome khi build)
org.gradle.jvmargs=-Xmx1536M -XX:MaxMetaspaceSize=384m -XX:ReservedCodeCacheSize=128m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Tat Daemon de giai phong RAM ngay sau khi build
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.configureondemand=true

android.useAndroidX=true
android.enableJetifier=true

# Vo hieu hoa Kotlin incremental compile de fix loi different roots o dia C/D tren Windows
kotlin.incremental=false
kotlin.incremental.multiplatform=false
