// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB26p95uIDbvEEWzBFkwMhyqO4OP-2Xt_s',
    appId: '1:179821265499:web:d1b8786d74a035cc0f357e',
    messagingSenderId: '179821265499',
    projectId: 'toeic-80ff0',
    authDomain: 'toeic-80ff0.firebaseapp.com',
    storageBucket: 'toeic-80ff0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9cb-OFFmJ7OWLKuV2Xp7iDV-Lae3u0lU',
    appId: '1:179821265499:android:62d5be87645736500f357e',
    messagingSenderId: '179821265499',
    projectId: 'toeic-80ff0',
    storageBucket: 'toeic-80ff0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnPZdf5vx6y7Ezs54bl28FykautVv0Byc',
    appId: '1:179821265499:ios:ade89a3501d7017c0f357e',
    messagingSenderId: '179821265499',
    projectId: 'toeic-80ff0',
    storageBucket: 'toeic-80ff0.firebasestorage.app',
    iosClientId: '179821265499-cic1l3s2d88vch0sm3vnv14p1e44rlrq.apps.googleusercontent.com',
    iosBundleId: 'com.example.toeicmobileapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnPZdf5vx6y7Ezs54bl28FykautVv0Byc',
    appId: '1:179821265499:ios:ade89a3501d7017c0f357e',
    messagingSenderId: '179821265499',
    projectId: 'toeic-80ff0',
    storageBucket: 'toeic-80ff0.firebasestorage.app',
    iosClientId: '179821265499-cic1l3s2d88vch0sm3vnv14p1e44rlrq.apps.googleusercontent.com',
    iosBundleId: 'com.example.toeicmobileapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB26p95uIDbvEEWzBFkwMhyqO4OP-2Xt_s',
    appId: '1:179821265499:web:f79d542ae54585c00f357e',
    messagingSenderId: '179821265499',
    projectId: 'toeic-80ff0',
    authDomain: 'toeic-80ff0.firebaseapp.com',
    storageBucket: 'toeic-80ff0.firebasestorage.app',
  );
}
